name: Publish package

on:
  release:
    types: [published]

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  publish_wheel:
    runs-on: ubuntu-latest
    needs: test
    container:
      image: python:3.8-slim
    steps:
      - # Upgrade git to the latest version so prevent errors in the following steps.
        name: install highest-version git
        run: |
          apt-get update
          apt-get install -y --upgrade git
      -
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: resolve dubious ownership of the repo
        run: git config --global --add safe.directory /__w/pytorch-to-onnx-checker/pytorch-to-onnx-checker
      -
        name: install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine
      -
        name: build wheel
        run: |
          python setup.py sdist bdist_wheel
      -
        name: get the resulting package version
        run: |
          echo "VERSION=$(echo $(ls dist/*.whl) | cut -d'/' -f2 | cut -d'-' -f2)" >> $GITHUB_ENV
      -
        name: check if version and release/tag name matches
        if: env.VERSION != github.ref_name
        run: exit 1
      -
        name: publish wheel
        run: >
          python -m twine upload dist/*
