name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

env:
  DOCKER_CONTAINER_NAME: ${USER}_pytorch-to-onnx-checker_github_action

jobs:
  run_tests:
    # For now, we will only add self-hosted
    # Feel free to add other hosts such as [X64, aip]
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Run tests
        run: |
          "pytest --cov pytorch-to-onnx-checker --cov-report=xml"
      -
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
